spring:
  application:
    name: project2_patientapi
  datasource:
    username: Joseb89
    password: Elessar1989!
    url: jdbc:postgresql://project2-sql.postgres.database.azure.com:5432/project2_jaab
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8082
  
