spring:
  application:
    name: project2_mainapi
  datasource:
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}
    url: ${AZURE_DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8081
  
